name: "Add New Question"
description: "Submit a new question to be added to the test."
title: "[Question]: "
labels: ["question", "auto-generate"]
assignees: []

body:
  - type: input
    id: title
    attributes:
      label: "Test Title"
      description: "Title of the test (e.g., 'Java Basics', 'Python Functions')"
      placeholder: "Enter the test title"
    validations:
      required: true

  - type: input
    id: file_name
    attributes:
      label: "File Name"
      description: "File to which this question belongs (e.g., java_test.json)"
      placeholder: "test_name.json"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: "Question"
      description: "Enter the question text"
      placeholder: "What is the output of print(2 + 3 * 4)?"
    validations:
      required: true

  - type: textarea
    id: options
    attributes:
      label: "Options"
      description: "List 4 options, one per line"
      placeholder: |
        14
        20
        24
        12
    validations:
      required: true

  - type: input
    id: correct
    attributes:
      label: "Correct Option Number"
      description: "Enter 1 for the first option, 2 for second, etc."
      placeholder: "1"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Solution"
      description: "Explain why this answer is correct."
      placeholder: "Multiplication has higher precedence, so 3*4=12, then 2+12=14."
    validations:
      required: true
