name: Convert Issue to Question File

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:

permissions:
  contents: write  # 👈 REQUIRED to allow push from github-actions bot

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: test  # Ensure we're on the correct branch

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install PyYAML

    - name: Parse Issue and Convert to JSON
      run: |
        echo '${{ toJson(github.event.issue) }}' > issue.json
        cat issue.json
        python .github/scripts/convert_github_issue_to_json.py

    - name: Commit the new question file
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add resources/
        git commit -m "Added question from issue #${{ github.event.issue.number }}"
        git push origin test
