name: Create Question JSON from Issue

on:
  issues:
    types: [opened, edited]

jobs:
  convert-issue-to-json:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Write issue event to file
        run: echo '${{ toJson(github.event) }}' > issue.json

      - name: Run script to convert issue to JSON
        run: python .github/scripts/convert_github_issue_to_json.py issue.json

      - name: Commit and push generated file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add resources/
          git commit -m "📄 Add question from issue: ${{ github.event.issue.title }}" || echo "Nothing to commit"
          git push origin test
