name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 python-docx

      - name: Lint with flake8
        run: |
          # Treat all errors as warnings and don't fail build
          flake8 . --exit-zero

      - name: Run matsci_mcq.py and generate document
        run: |
          python3 matsci_mcq.py

      - name: Upload .docx as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcq-doc
          path: "*.docx"

      - name: Create GitHub issue with artifact info
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "MCQ Document Generated",
              body: "A new MCQ document was generated. [Download it from the Actions artifacts](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${{ github.run_id }})"
            })
